#!/usr/bin/env python
#################################################################################
# Copyright 2018 ROBOTIS CO., LTD.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#################################################################################

# Authors: Gilbert #

import rospy
import os
import json
import numpy as np
import random
import time
import sys
sys.path.append(os.path.dirname(os.path.abspath(os.path.dirname(__file__))))
from collections import deque
from std_msgs.msg import Float32MultiArray
from src.turtlebot3_dqn.environment_stage_1_rl import Env
from keras.models import Sequential, load_model
from keras.optimizers import RMSprop
from keras.layers import Dense, Dropout, Activation

import pandas as pd
import csv

import sys
try:
    import queue
except ImportError:
    import Queue as queue
import traceback
import json
import ch_consumer

consumer_queue = queue.Queue(2048)

try:
    print('start thread')
    ch_consumer_thread = ch_consumer.ChConsumer(consumer_queue)
    ch_consumer_thread.start()
except:
    traceback.print_exc()
    print(sys.exc_info()[0])
    sys.exit(1)

import datetime

LEARN = 50 # 10
EPISODES = 505 # 505
METRIC_NAME = "ubuntu_A_2"

class ReinforceAgent():
    def __init__(self, state_size, action_size):
        self.pub_result = rospy.Publisher('result', Float32MultiArray, queue_size=5)
        self.dirPath = os.path.dirname(os.path.realpath(__file__))
        self.dirPath = self.dirPath.replace('turtlebot3_dqn/nodes', 'turtlebot3_dqn/save_model/stage_1_')
        self.result = Float32MultiArray()

        self.load_model = False
        self.load_episode = 0
        self.state_size = state_size
        self.action_size = action_size
        self.episode_step = 6000
        self.target_update = 2000
        self.discount_factor = 0.99
        self.learning_rate = 0.00025
        self.epsilon = 1.0 # 1.0
        self.epsilon_decay = 0.99 # 0.99
        self.epsilon_min = 0.05
        self.batch_size = 64
        self.train_start = 64
        self.memory = deque(maxlen=1000000)

        # self.q_value = np.zeros(self.action_size)

        self.model = self.buildModel()
        self.target_model = self.buildModel()

        self.updateTargetModel()

        if self.load_model:
            self.model.set_weights(load_model(self.dirPath+str(self.load_episode)+".h5").get_weights())

            with open(self.dirPath+str(self.load_episode)+'.json') as outfile:
                param = json.load(outfile)
                self.epsilon = param.get('epsilon')

    def buildModel(self):
        model = Sequential()
        dropout = 0.2

        model.add(Dense(64, input_shape=(self.state_size,), activation='relu', kernel_initializer='lecun_uniform'))
        model.add(Dense(64, activation='relu', kernel_initializer='lecun_uniform'))
        model.add(Dropout(dropout))

        model.add(Dense(self.action_size, kernel_initializer='lecun_uniform'))
        model.add(Activation('linear'))
        model.compile(loss='mse', optimizer=RMSprop(lr=self.learning_rate, rho=0.9, epsilon=1e-06))
        model.summary()

        return model

    def getQvalue(self, reward, next_target, done):
        if done:
            return reward
        else:
            return reward + self.discount_factor * np.amax(next_target)

    def updateTargetModel(self):
        self.target_model.set_weights(self.model.get_weights())

    def getAction(self, state):
        rand = np.random.rand()
        if  rand <= self.epsilon:
            self.q_value = np.zeros(self.action_size)
            return random.randrange(self.action_size)
            # rand_choice = np.random.choice([0, 1, 2, 3, 4, 5], p=[1.0,0.0,0.0,0.0,0.0,0.0])
            # return rand_choice
        else:
            q_value = self.model.predict(state.reshape(1, len(state)))
            self.q_value = q_value
            return np.argmax(q_value[0])

    def appendMemory(self, state, action, reward, next_state, done):
        self.memory.append((state, action, reward, next_state, done))

    def trainModel(self, target=False):
        mini_batch = random.sample(self.memory, self.batch_size)
        X_batch = np.empty((0, self.state_size), dtype=np.float64)
        Y_batch = np.empty((0, self.action_size), dtype=np.float64)

        for i in range(self.batch_size):
            states = mini_batch[i][0]
            actions = mini_batch[i][1]
            rewards = mini_batch[i][2]
            next_states = mini_batch[i][3]
            dones = mini_batch[i][4]

            q_value = self.model.predict(states.reshape(1, len(states)))
            self.q_value = q_value

            if target:
                next_target = self.target_model.predict(next_states.reshape(1, len(next_states)))
            else:
                next_target = self.model.predict(next_states.reshape(1, len(next_states)))

            next_q_value = self.getQvalue(rewards, next_target, dones)

            X_batch = np.append(X_batch, np.array([states.copy()]), axis=0)
            Y_sample = q_value.copy()

            Y_sample[0][actions] = next_q_value
            Y_batch = np.append(Y_batch, np.array([Y_sample[0]]), axis=0)

            if dones:
                X_batch = np.append(X_batch, np.array([next_states.copy()]), axis=0)
                Y_batch = np.append(Y_batch, np.array([[rewards] * self.action_size]), axis=0)

        self.model.fit(X_batch, Y_batch, batch_size=self.batch_size, epochs=1, verbose=0)

if __name__ == '__main__':
    rospy.init_node('turtlebot3_dqn_stage_1')
    num_agent = 3
    agent_topics = ["tb3_{}".format(i) for i in range(num_agent)]
    pub_results = [rospy.Publisher(topic + '/result', Float32MultiArray, queue_size=5) for topic in agent_topics]
    pub_get_actions = [rospy.Publisher(topic + '/get_action', Float32MultiArray, queue_size=5) for topic in agent_topics]
    results = [Float32MultiArray() for _ in agent_topics] # range(num_agent)
    get_actions = [Float32MultiArray() for _ in agent_topics]
    
    for learn in range(LEARN):
        state_size = 9 # 12
        action_size = 9

        env = Env(num_agent, action_size)
        agents = [ReinforceAgent(state_size, action_size) for _ in agent_topics]

        scores, episodes = [], []
        global_step = 0
        start_time = time.time()
        now = datetime.datetime.now()

        current_time = now.strftime("%H:%M:%S")
        FIENAME = '/home/rtos-ubuntu/Result_Data/ubuntu_A_' + current_time + '.csv'

        for e in range(agents[0].load_episode + 1, EPISODES):
            done = False
            dones = [False for _ in agent_topics]
            states, pxes = env.reset()
            score = 0
            scores = [0 for _ in agent_topics] # range(num_agent)
            actions = [0 for _ in agent_topics]
            for t in range(agents[0].episode_step):
                actions[1] = agents[1].getAction(states[1])
                actions[1] = 5 # 5
                actions[2] = agents[2].getAction(states[2])
                actions[2] = 3 # 3
                # state1[0] = action2
                # state1[1] = action3
                actions[0] = agents[0].getAction(states[0])
                # print(state1)
                # print(agents[0].q_value)

                next_states, rewards, dones, next_pxes = env.step(actions, [agent_topics[i] + "/scan" for i in range(num_agent)])
                # next_state1, reward1, done1, next_px1 = env.step(actions[0], "tb3_0/scan")
                # next_state2, reward2, done2, next_px2 = env.step(actions[1], "tb3_1/scan")
                # next_state3, reward3, done3, next_px3 = env.step(actions[2], "tb3_2/scan")
                done = dones[0] or dones[1] or dones[2]

                rewards[0] = (next_pxes[0] - pxes[0]) * 100 + rewards[0] #
                rewards[1] = (next_pxes[1] - pxes[1]) * 100 + rewards[1]
                rewards[2] = (next_pxes[2] - pxes[2]) * 100 + rewards[2]
                
                agents[0].appendMemory(states[0], actions[0], rewards[0], next_states[0], dones[0])
                agents[1].appendMemory(states[1], actions[1], rewards[1], next_states[1], dones[1])
                agents[2].appendMemory(states[2], actions[2], rewards[2], next_states[2], dones[2])

                if len(agents[0].memory) >= agents[0].train_start:
                    if global_step <= agents[0].target_update:
                        agents[0].trainModel()
                    else:
                        agents[0].trainModel(True)

                if len(agents[1].memory) >= agents[1].train_start:
                    if global_step <= agents[1].target_update:
                        agents[1].trainModel()
                    else:
                        agents[1].trainModel(True)

                if len(agents[2].memory) >= agents[2].train_start:
                    if global_step <= agents[2].target_update:
                        agents[2].trainModel()
                    else:
                        agents[2].trainModel(True)

                scores[0] += rewards[0]
                scores[1] += rewards[1]
                scores[2] += rewards[2]
                score = scores[0] + scores[1] + scores[2] # 

                states[0] = next_states[0]
                states[1] = next_states[1]
                states[2] = next_states[2]
                pxes[0] = next_pxes[0]
                pxes[1] = next_pxes[1]
                pxes[2] = next_pxes[2]

                get_actions[0].data = [actions[0], scores[0], rewards[0]]
                get_actions[1].data = [actions[1], scores[1], rewards[1]]
                get_actions[2].data = [actions[2], scores[2], rewards[2]]

                pub_get_actions[0].publish(get_actions[0])
                pub_get_actions[1].publish(get_actions[1])
                pub_get_actions[2].publish(get_actions[2])

                if e % 10 == 0:
                    agents[0].model.save(agents[0].dirPath + str(e) + '.h5')
                    with open(agents[0].dirPath + str(e) + '.json', 'w') as outfile:
                        json.dump(param_dictionary1, outfile)

                if e % 10 == 0:
                    agents[1].model.save(agents[1].dirPath + str(e) + '.h5')
                    with open(agents[1].dirPath + str(e) + '.json', 'w') as outfile:
                        json.dump(param_dictionary2, outfile)

                if e % 10 == 0:
                    agents[2].model.save(agents[2].dirPath + str(e) + '.h5')
                    with open(agents[2].dirPath + str(e) + '.json', 'w') as outfile:
                        json.dump(param_dictionary3, outfile)

                if t >= 500:
                    rospy.loginfo("Time out!!")
                    done = True

                if done:
                    print(e)
                    list_json = []
                    # result.data = [score, (np.max(agent1.q_value) + np.max(agent2.q_value) + np.max(agent3.q_value)) / 3]
                    results[0].data = [scores[0], np.max(agents[0].q_value)]
                    results[1].data = [scores[1], np.max(agents[1].q_value)]
                    results[2].data = [scores[2], np.max(agents[2].q_value)]
                    # pub_result.publish(result)
                    pub_results[0].publish(results[0])
                    pub_results[1].publish(results[1])
                    pub_results[2].publish(results[2])

                    unix_time = int(time.time())

                    if os.path.isfile(FIENAME) == False:
                        open(FIENAME, 'w')
                    with open(FIENAME, 'a') as f:
                        wr = csv.writer(f)
                        wr.writerow(results[0].data)

                    
                    agents[0].updateTargetModel()
                    agents[1].updateTargetModel()
                    agents[2].updateTargetModel()
                    scores.append(score)
                    episodes.append(e)
                    m, s = divmod(int(time.time() - start_time), 60)
                    h, m = divmod(m, 60)
                    # rospy.loginfo('Ep: %d score: %.2f memory: %d epsilon: %.2f time: %d:%02d:%02d',
                    #               e, score, h, m, s)
                    rospy.loginfo('Ep: %d score: %.2f memory: %d epsilon: %.2f time: %d:%02d:%02d',
                                e, scores[0], len(agents[0].memory), agents[0].epsilon, h, m, s)
                    rospy.loginfo('Ep: %d score: %.2f memory: %d epsilon: %.2f time: %d:%02d:%02d',
                                e, scores[1], len(agents[1].memory), agents[1].epsilon, h, m, s)
                    rospy.loginfo('Ep: %d score: %.2f memory: %d epsilon: %.2f time: %d:%02d:%02d',
                                e, scores[2], len(agents[2].memory), agents[2].epsilon, h, m, s)
                    param_keys = ['epsilon']
                    param_values1 = [agents[0].epsilon]
                    param_values2 = [agents[1].epsilon]
                    param_values3 = [agents[2].epsilon]
                    param_dictionary1 = dict(zip(param_keys, param_values1))
                    param_dictionary2 = dict(zip(param_keys, param_values2))
                    param_dictionary3 = dict(zip(param_keys, param_values3))
                    break
                
                global_step += 1
                if global_step % agents[0].target_update == 0:
                    rospy.loginfo("UPDATE TARGET NETWORK")

            if agents[0].epsilon > agents[0].epsilon_min:
                agents[0].epsilon *= agents[0].epsilon_decay
            if agents[1].epsilon > agents[1].epsilon_min:
                agents[1].epsilon *= agents[1].epsilon_decay
            if agents[2].epsilon > agents[2].epsilon_min:
                agents[2].epsilon *= agents[2].epsilon_decay
